name: running other workflow file

on:
  workflow_dispatch:
    inputs:
      stackname:
        description: Select stack
        default: defaultacc
        required: true
        type: choice
        options:
          - acctest1
          - acctest2
          - acctest3
          - defaultacc
      shared-env:
        required: false
    secrets:
      MYTOKEN:
        required: true

env:
  TESTINGENV: "heheh ini env test"

jobs:
  set-env-variables:
    runs-on: ubuntu-latest
    outputs:
      shared-env: ${{ steps.set-env-for-accname.outputs.shared-env }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Variable from Shell
        shell: bash
        run: |
          pwd
          ls -lah
          ./scripts/variables.sh ${{ github.event.inputs.stackname }}

      - name: test the choice
        shell: bash
        run: |
          echo "this is the account : ${{ env.ACCOUNTNAME }}"
      
      - name: set the output
        shell: bash
        id: set-env-for-accname
        run: |
          echo "::set-output name=shared-env::${{ env.ACCOUNTNAME }}"

      - name: test the shared
        run: echo "this is env ======== ${{ needs.set-env-variables.outputs.shared-env }}"

  runothers:
    needs: [set-env-variables]
    uses: auzty/devops-worklow/.github/workflows/callmefromothers.yml@main
    with:
      shared-env: ${{needs.set-env-variables.outputs.shared-env}}