name: running other workflow file

on:
  workflow_dispatch:
    inputs:
      stackname:
        description: Select stack
        default: defaultacc
        required: true
        type: choice
        options:
          - acctest1
          - acctest2
          - acctest3
          - defaultacc

jobs:
  set-env-variables:
    runs-on: ubuntu-latest
    outputs:
      shared-accname: ${{ steps.set-env-for-accname.outputs.accname }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Variable from Shell
        shell: bash
        run: |
          ./scripts/variables.sh ${{ github.event.inputs.stackname }}

      - name: test the choice
        shell: bash
        run: |
          echo "this is the account : ${{ env.ACCOUNTNAME }}"
      
      - name: set the output
        shell: bash
        id: set-env-for-accname
        run: |
          echo "::set-output name=accname::${{ env.ACCOUNTNAME }}"

  runothers:
    needs: [set-env-variables]
    uses: auzty/devops-worklow/.github/workflows/callmefromothers.yml@main
    with:
      shared-accname: ${{needs.set-env-variables.outputs.shared-accname}}
      mytoken: ${{secrets.mytoken}}