name: running other workflow file

on:
  workflow_dispatch:
    inputs:
      deployType:
        description: 'Deploying Manual'
        required: true
        default: 'staging' 
        type: choice
        options:
        - staging
        - prod
      shared-env:
        required: false
    secrets:
      MYTOKEN:
        required: true

env:
  TESTINGENV: "heheh ini env test"

permissions:
  id-token: write
  contents: read

jobs:
  deploystage:
    runs-on: ubuntu-latest
    outputs:
      shared-env: ${{ steps.set-env-to-others.outputs.shared-env}}
    steps:
      - name: fisrt check env on main yaml
        run: echo "this is called on main yaml ->>>>> ${{env.TESTINGENV}}"
      - name: checkout another repo 
        uses: actions/checkout@v3
        with:
          repository: "auzty/devops-worklow"
          token: ${{secrets.MYTOKEN}}
          path: devops-workflow
      - name: init the env from first yaml
        id: set-env-to-others
        run: |
          echo "::set-output name=shared-env::${{env.TESTINGENV}}"
        
  runothers:
    needs: [deploystage]
    uses: auzty/devops-worklow/.github/workflows/callmefromothers.yml@main
    with:
      shared-env: ${{needs.deploystage.outputs.shared-env}}
    secrets:
      ACCESS_TOKEN_KU: ${{secrets.MYTOKEN}}