name: running other workflow file

on:
  workflow_dispatch:
    inputs:
      stackname:
        description: Select stack
        default: defaultacc
        required: true
        type: choice
        options:
          - acctest1
          - acctest2
          - acctest3
          - defaultacc
    secrets:
      MYTOKEN:
        required: true

env:
  TESTINGENV: "heheh ini env test"

jobs:
  set-env-variables:
    runs-on: ubuntu-latest
    outputs:
      shared-accname: ${{ steps.set-env-for-accname.outputs.acc-name }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Variable from Shell
        shell: bash
        run: |
          pwd
          ls -lah
          ./scripts/variables.sh ${{ github.event.inputs.stackname }}

      - name: test the choice
        shell: bash
        run: |
          echo "this is the account : ${{ env.ACCOUNTNAME }}"
      
      - name: set the output
        shell: bash
        id: set-env-for-accname
        run: |
          echo "::set-output name=acc-name::${{ env.ACCOUNTNAME }}"

#  deploystage:
#    runs-on: ubuntu-latest
#    outputs:
#      shared-env: ${{ steps.set-env-to-others.outputs.shared-env}}
#    steps:
#      - name: fisrt check env on main yaml
#        run: echo "this is called on main yaml ->>>>> ${{env.TESTINGENV}}"
#      - name: checkout another repo 
#        uses: actions/checkout@v3
#        with:
#          repository: "auzty/devops-worklow"
#          token: ${{secrets.MYTOKEN}}
#          path: devops-workflow
#      - name: init the env from first yaml
#        id: set-env-to-others
#        run: |
#          echo "::set-output name=shared-env::${{env.TESTINGENV}}"
        
  runothers:
    needs: [set-env-variables]
    uses: auzty/devops-worklow/.github/workflows/callmefromothers.yml@main
    with:
      shared-env: ${{needs.set-env-variables.outputs.shared-accname}}
    secrets:
      ACCESS_TOKEN_KU: ${{secrets.MYTOKEN}}