name: running other workflow file

on:
  workflow_dispatch:
    inputs:
      deployType:
        description: 'Deploying Manual'
        required: true
        default: 'staging' 
        type: choice
        options:
        - staging
        - prod
    secrets:
      MYTOKEN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploystage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout another repo 
        uses: actions/checkout@v3
        with:
          repository: "auzty/devops-worklow"
          token: ${{secrets.MYTOKEN}}
          path: devops-workflow
  runothers:
    uses: auzty/devops-worklow/.github/workflows/callmefromothers.yml@main
    secrets:
      mytoken: ${{secrets.MYTOKEN}}