name:  testing json
#on:
#  push:
#    branches:
#      - "testenv"
on:
  workflow_dispatch:
    inputs:
      stackname:
        description: Select stack
        default: defaultacc
        required: true
        type: choice
        options:
          - DEV10
          - DEV11

jobs:
  set-env-variables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: testlisting
        run: ls -lah

      - name: Set the value in bash
        id: step_one
        run: |
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          cat myjson.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: listing
        run: |
          echo "${{fromJson(env.JSON_RESPONSE)}}"

      - name: selecting env using jq
        uses: sergeysova/jq-action@v2
        id: selectedjson
        with:
          cmd: 'jq .${{ github.event.inputs.stackname }}'

      - name: testing the results
        run:  echo ${{ fromJson(steps.selectedjson.output) }}
#      - name: testing the env
#        run: echo $${{github.event.inputs.stackname}}_REGION