name: localstack-dynamodb
on:
  workflow_dispatch:
    inputs:
      stackname:
        description: Select stack
        default: defaultacc
        required: true
        type: choice
        options:
          - DEV10
          - DEV11
jobs:
  define-service:
    runs-on: ubuntu-latest
    services:
      run-localstack:
        image: localstack/localstack
        # Set health checks to wait until postgres has started
        ports:
           - 4566:4566
           - 4510-4559:4510-4559
           
    steps:
      - name: Start LocalStack
        run: |
          pip install awscli-local[ver1] # install LocalStack cli and awslocal          
          echo "Waiting for LocalStack startup..."  # Wait 30 seconds for the LocalStack container
          # localstack wait -t 30                     # to become ready before timing out 
          echo "Startup complete"          
      - name: Run some Tests against LocalStack
        run: |
          awslocal s3 mb s3://test
          awslocal s3 ls
          echo "Test S3 Bucket Execution complete!"
          
      - name: test Dynamodb against localstack
        run: |
          awslocal dynamodb create-table --table-name jajal --attribute-definitions AttributeName=Nama,AttributeType=S --key-schema AttributeName=Nama,KeyType=HASH --provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=55
          awslocal dynamodb describe-table --table-name jajal | grep TableStatus
          awslocal dynamodb put-item --table-name jajal --item '{"Nama":{"S":"Yusuf"}'
          awslocal dynamodb scan --table-name jajal
