name:  testing json
#on:
#  push:
#    branches:
#      - "testenv"
on:
  workflow_dispatch:
    inputs:
      stackname:
        description: Select stack
        default: defaultacc
        required: true
        type: choice
        options:
          - DEV10
          - DEV11

jobs:
  set-env-variables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: testenv

      - name: Setup Variable from json file
        id: set_json
        run: |
          echo 'MYJSON<<EOF' >> $GITHUB_ENV
          cat myjson.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: listing
        run: |
          echo "${{fromJson(env.MYJSON)}} | jq"

#      - name: testing the env
#        run: echo $${{github.event.inputs.stackname}}_REGION