name: localstack-aws-cli
on:
  workflow_dispatch:
    inputs:
      stackname:
        description: Select stack
        default: defaultacc
        required: true
        type: choice
        options:
          - DEV10
          - DEV11
jobs:
  define-service:
    runs-on: ubuntu-latest
    services:
      run-localstack:
        image: localstack/localstack
        # Set health checks to wait until postgres has started
        ports:
           - 4566:4566
           - 4510-4559:4510-4559
           
    steps: 
      - name: Run some Tests against LocalStack
        run: |
          aws --endpoint-url=http://localhost:4566 s3 mb s3://test
          aws --endpoint-url=http://localhost:4566 s3 ls
          aws --endpoint-url=http://localhost:4566 "Test S3 Bucket Execution complete!"
          
      - name: test Dynamodb against localstack
        run: |
          aws --endpoint-url=http://localhost:4566 dynamodb create-table --table-name jajal --attribute-definitions AttributeName=Nama,AttributeType=S --key-schema AttributeName=Nama,KeyType=HASH --provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=55
          aws --endpoint-url=http://localhost:4566 dynamodb describe-table --table-name jajal | grep TableStatus
          aws --endpoint-url=http://localhost:4566 dynamodb put-item --table-name jajal --item '{"Nama":{"S":"Yusuf"}}'
          aws --endpoint-url=http://localhost:4566 dynamodb scan --table-name jajal
