name: localstack-action-example
on:
  workflow_dispatch:
    inputs:
      stackname:
        description: Select stack
        default: defaultacc
        required: true
        type: choice
        options:
          - DEV10
          - DEV11
jobs:
  define-service:
    runs-on: ubuntu-latest
    services:
      run-localstack:
        image: localstack/localstack
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
        # Set health checks to wait until postgres has started
        ports:
           - 4566:4566
           - 4510-4559:4510-4559
           
    steps:
      - name: Start LocalStack
        run: |
          pip install awscli-local[ver1] # install LocalStack cli and awslocal          
          echo "Waiting for LocalStack startup..."  # Wait 30 seconds for the LocalStack container
          localstack wait -t 30                     # to become ready before timing out 
          echo "Startup complete"          
      - name: Run some Tests against LocalStack
        run: |
          awslocal s3 mb s3://test
          awslocal s3 ls
          echo "Test Execution complete!"
