name:  testing env
#on:
#  push:
#    branches:
#      - "testenv"
on:
  workflow_dispatch:
    inputs:
      stackname:
        description: Select stack
        default: defaultacc
        required: true
        type: choice
        options:
          - DEV10
          - DEV11

jobs:
  set-env-variables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Variable from Shell
        id: settingenv
        uses: cardinalby/export-env-action@v1
        with:
          envFile: 'myenv.env'    
          expand: 'true'

      - name: listing
        run: echo ${{ steps.settingenv.outputs}}

      - name: testing the env
        run: echo $${{github.event.inputs.stackname}}_REGION