name:  testing json
#on:
#  push:
#    branches:
#      - "testenv"
on:
  workflow_dispatch:
    inputs:
      stackname:
        description: Select stack
        default: defaultacc
        required: true
        type: choice
        options:
          - DEV10
          - DEV11

jobs:
  set-env-variables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: testlisting
        run: ls -lah

      - name: Set the value in bash
        id: step_one
        run: |
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          curl https://jsonplaceholder.typicode.com/todos/1 >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

#      - name: testing the env
#        run: echo $${{github.event.inputs.stackname}}_REGION